name: LAMP Deployement 

on: 
    workflow_dispatch:
jobs:
  linting: 
    name: Lint Ansible files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: action/checkout@v2
      - name: linting
        uses: ansible/ansible-lint-action@v2.6.1
        with:
          targets:
           ./playbook.yml
           ./inventory.yml
          

