name: LAMP Deployement 

on: 
    workflow_dispatch:
jobs:
  linting: 
    name: Lint Ansible files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: action/checkout@v2
      - name: linting
        uses: ansible/ansible-lint-action@eb92667e07cc18e1d115ff02e5f07126310cec11
        with:
          targets:
            playbook.yml
            inventory.yml
          

